# Import

In [3]:
!pip install requests

Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.11/site-packages (from requests) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.11/site-packages (from requests) (2023.7.22)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Installing collected packages: requests
Successfully installed requests-2.31.0

In [4]:
import requests
import json

# Get data from API
def get_data_from_api(api_url):
    try:
        response = requests.get(api_url)
        response.raise_for_status()  # Check for any request errors

        data = response.json()  # Parse the JSON data from the response

        return data
    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")
        return None

# Save data to JSON file
def save_data_to_json(data, file_path):
    try:
        with open(file_path, 'w') as json_file:
            json.dump(data, json_file, indent=4)
        print(f"Data saved to {file_path}")
    except Exception as e:
        print(f"Error saving data to JSON file: {e}")

In [5]:
# Main program to get the data from the API and save it to a JSON file
api_url = "https://swapi.dev/api/"  
output_file = "dataLinks.json"  # Specify the path and filename for the JSON file

data = get_data_from_api(api_url)

if data:
    save_data_to_json(data, output_file)

Data saved to dataLinks.json

In [6]:
import pandas as pd
# import numpy as np
import sqlite3

In [7]:
path = '{path}.json' 

# Read JSON file
allData = pd.read_json(path.format(path='dataLinks'), orient='index')

display(allData)

                                          0
people        https://swapi.dev/api/people/
planets      https://swapi.dev/api/planets/
films          https://swapi.dev/api/films/
species      https://swapi.dev/api/species/
vehicles    https://swapi.dev/api/vehicles/
starships  https://swapi.dev/api/starships/

In [8]:
# Get results from API and save to JSON file
listObj = []
def get_results_from_api(api_url,output_file):
   
  data = get_data_from_api(api_url)
  for x in data['results']:
    listObj.append(x)

  if data['next']: # True or False
    get_results_from_api(data['next'],output_file)
  else:
    save_data_to_json(listObj, output_file)
    listObj.clear()

rowCount = 0
for eachLink in list(allData[0]):
  get_results_from_api(eachLink,allData.index[rowCount]+".json")
  rowCount += 1

Data saved to people.json
Data saved to planets.json
Data saved to films.json
Data saved to species.json
Data saved to vehicles.json
Data saved to starships.json

# Extract

In [9]:
path = '{path}.json'

# Read JSON file
df_people_extracted = pd.read_json(path.format(path='people'))
df_planets_extracted = pd.read_json(path.format(path='planets'))
df_films_extracted = pd.read_json(path.format(path='films'))
df_species_extracted = pd.read_json(path.format(path='species'))
df_vehicles_extracted = pd.read_json(path.format(path='vehicles'))
df_starships_extracted = pd.read_json(path.format(path='starships'))

In [10]:
print('people')
display(df_people_extracted.tail(20))

people

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
62,Luminara Unduli,170,56.2,black,yellow,blue,58BBY,female,https://swapi.dev/api/planets/51/,"[https://swapi.dev/api/films/5/, https://swapi...",[https://swapi.dev/api/species/29/],[],[],2014-12-20T16:45:53.668000Z,2014-12-20T21:17:50.455000Z,https://swapi.dev/api/people/64/
63,Barriss Offee,166,50,black,yellow,blue,40BBY,female,https://swapi.dev/api/planets/51/,[https://swapi.dev/api/films/5/],[https://swapi.dev/api/species/29/],[],[],2014-12-20T16:46:40.440000Z,2014-12-20T21:17:50.457000Z,https://swapi.dev/api/people/65/
64,Dormé,165,unknown,brown,light,brown,unknown,female,https://swapi.dev/api/planets/8/,[https://swapi.dev/api/films/5/],[https://swapi.dev/api/species/1/],[],[],2014-12-20T16:49:14.640000Z,2014-12-20T21:17:50.460000Z,https://swapi.dev/api/people/66/
65,Dooku,193,80,white,fair,brown,102BBY,male,https://swapi.dev/api/planets/52/,"[https://swapi.dev/api/films/5/, https://swapi...",[https://swapi.dev/api/species/1/],[https://swapi.dev/api/vehicles/55/],[],2014-12-20T16:52:14.726000Z,2014-12-20T21:17:50.462000Z,https://swapi.dev/api/people/67/
66,Bail Prestor Organa,191,unknown,black,tan,brown,67BBY,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/5/, https://swapi...",[https://swapi.dev/api/species/1/],[],[],2014-12-20T16:53:08.575000Z,2014-12-20T21:17:50.463000Z,https://swapi.dev/api/people/68/
67,Jango Fett,183,79,black,tan,brown,66BBY,male,https://swapi.dev/api/planets/53/,[https://swapi.dev/api/films/5/],[],[],[],2014-12-20T16:54:41.620000Z,2014-12-20T21:17:50.465000Z,https://swapi.dev/api/people/69/
68,Zam Wesell,168,55,blonde,"fair, green, yellow",yellow,unknown,female,https://swapi.dev/api/planets/54/,[https://swapi.dev/api/films/5/],[https://swapi.dev/api/species/30/],[https://swapi.dev/api/vehicles/45/],[],2014-12-20T16:57:44.471000Z,2014-12-20T21:17:50.468000Z,https://swapi.dev/api/people/70/
69,Dexter Jettster,198,102,none,brown,yellow,unknown,male,https://swapi.dev/api/planets/55/,[https://swapi.dev/api/films/5/],[https://swapi.dev/api/species/31/],[],[],2014-12-20T17:28:27.248000Z,2014-12-20T21:17:50.470000Z,https://swapi.dev/api/people/71/
70,Lama Su,229,88,none,grey,black,unknown,male,https://swapi.dev/api/planets/10/,[https://swapi.dev/api/films/5/],[https://swapi.dev/api/species/32/],[],[],2014-12-20T17:30:50.416000Z,2014-12-20T21:17:50.473000Z,https://swapi.dev/api/people/72/
71,Taun We,213,unknown,none,grey,black,unknown,female,https://swapi.dev/api/planets/10/,[https://swapi.dev/api/films/5/],[https://swapi.dev/api/species/32/],[],[],2014-12-20T17:31:21.195000Z,2014-12-20T21:17:50.474000Z,https://swapi.dev/api/people/73/
72,Jocasta Nu,167,unknown,white,fair,blue,unknown,female,https://swapi.dev/api/planets/9/,[https://swapi.dev/api/films/5/],[https://swapi.dev/api/species/1/],[],[],2014-12-20T17:32:51.996000Z,2014-12-20T21:17:50.476000Z,https://swapi.dev/api/people/74/
73,R4-P17,96,unknown,none,"silver, red","red, blue",unknown,female,https://swapi.dev/api/planets/28/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],2014-12-20T17:43:36.409000Z,2014-12-20T21:17:50.478000Z,https://swapi.dev/api/people/75/
74,Wat Tambor,193,48,none,"green, grey",unknown,unknown,male,https://swapi.dev/api/planets/56/,[https://swapi.dev/api/films/5/],[https://swapi.dev/api/species/33/],[],[],2014-12-20T17:53:52.607000Z,2014-12-20T21:17:50.481000Z,https://swapi.dev/api/people/76/
75,San Hill,191,unknown,none,grey,gold,unknown,male,https://swapi.dev/api/planets/57/,[https://swapi.dev/api/films/5/],[https://swapi.dev/api/species/34/],[],[],2014-12-20T17:58:17.049000Z,2014-12-20T21:17:50.484000Z,https://swapi.dev/api/people/77/
76,Shaak Ti,178,57,none,"red, blue, white",black,unknown,female,https://swapi.dev/api/planets/58/,"[https://swapi.dev/api/films/5/, https://swapi...",[https://swapi.dev/api/species/35/],[],[],2014-12-20T18:44:01.103000Z,2014-12-20T21:17:50.486000Z,https://swapi.dev/api/people/78/
77,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/36/],[https://swapi.dev/api/vehicles/60/],[https://swapi.dev/api/starships/74/],2014-12-20T19:43:53.348000Z,2014-12-20T21:17:50.488000Z,https://swapi.dev/api/people/79/
78,Tarfful,234,136,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/3/],[],[],2014-12-20T19:46:34.209000Z,2014-12-20T21:17:50.491000Z,https://swapi.dev/api/people/80/
79,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-20T19:49:35.583000Z,2014-12-20T21:17:50.493000Z,https://swapi.dev/api/people/81/
80,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],2014-12-20T20:18:37.619000Z,2014-12-20T21:17:50.496000Z,https://swapi.dev/api/people/82/
81,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/37/],[],[],2014-12-20T20:35:04.260000Z,2014-12-20T21:17:50.498000Z,https://swapi.dev/api/people/83/

In [11]:
print('planets')
display(df_planets_extracted)

planets

,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url
0,Tatooine,23,304,10465,arid,1 standard,desert,1,200000,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-09T13:50:49.641000Z,2014-12-20T20:58:18.411000Z,https://swapi.dev/api/planets/1/
1,Alderaan,24,364,12500,temperate,1 standard,"grasslands, mountains",40,2000000000,"[https://swapi.dev/api/people/5/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T11:35:48.479000Z,2014-12-20T20:58:18.420000Z,https://swapi.dev/api/planets/2/
2,Yavin IV,24,4818,10200,"temperate, tropical",1 standard,"jungle, rainforests",8,1000,[],[https://swapi.dev/api/films/1/],2014-12-10T11:37:19.144000Z,2014-12-20T20:58:18.421000Z,https://swapi.dev/api/planets/3/
3,Hoth,23,549,7200,frozen,1.1 standard,"tundra, ice caves, mountain ranges",100,unknown,[],[https://swapi.dev/api/films/2/],2014-12-10T11:39:13.934000Z,2014-12-20T20:58:18.423000Z,https://swapi.dev/api/planets/4/
4,Dagobah,23,341,8900,murky,N/A,"swamp, jungles",8,unknown,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,https://swapi.dev/api/planets/5/
5,Bespin,12,5110,118000,temperate,"1.5 (surface), 1 standard (Cloud City)",gas giant,0,6000000,[https://swapi.dev/api/people/26/],[https://swapi.dev/api/films/2/],2014-12-10T11:43:55.240000Z,2014-12-20T20:58:18.427000Z,https://swapi.dev/api/planets/6/
6,Endor,18,402,4900,temperate,0.85 standard,"forests, mountains, lakes",8,30000000,[https://swapi.dev/api/people/30/],[https://swapi.dev/api/films/3/],2014-12-10T11:50:29.349000Z,2014-12-20T20:58:18.429000Z,https://swapi.dev/api/planets/7/
7,Naboo,26,312,12120,temperate,1 standard,"grassy hills, swamps, forests, mountains",12,4500000000,"[https://swapi.dev/api/people/3/, https://swap...","[https://swapi.dev/api/films/3/, https://swapi...",2014-12-10T11:52:31.066000Z,2014-12-20T20:58:18.430000Z,https://swapi.dev/api/planets/8/
8,Coruscant,24,368,12240,temperate,1 standard,"cityscape, mountains",unknown,1000000000000,"[https://swapi.dev/api/people/34/, https://swa...","[https://swapi.dev/api/films/3/, https://swapi...",2014-12-10T11:54:13.921000Z,2014-12-20T20:58:18.432000Z,https://swapi.dev/api/planets/9/
9,Kamino,27,463,19720,temperate,1 standard,ocean,100,1000000000,"[https://swapi.dev/api/people/22/, https://swa...",[https://swapi.dev/api/films/5/],2014-12-10T12:45:06.577000Z,2014-12-20T20:58:18.434000Z,https://swapi.dev/api/planets/10/
10,Geonosis,30,256,11370,"temperate, arid",0.9 standard,"rock, desert, mountain, barren",5,100000000000,[https://swapi.dev/api/people/63/],[https://swapi.dev/api/films/5/],2014-12-10T12:47:22.350000Z,2014-12-20T20:58:18.437000Z,https://swapi.dev/api/planets/11/
11,Utapau,27,351,12900,"temperate, arid, windy",1 standard,"scrublands, savanna, canyons, sinkholes",0.9,95000000,[https://swapi.dev/api/people/83/],[https://swapi.dev/api/films/6/],2014-12-10T12:49:01.491000Z,2014-12-20T20:58:18.439000Z,https://swapi.dev/api/planets/12/
12,Mustafar,36,412,4200,hot,1 standard,"volcanoes, lava rivers, mountains, caves",0,20000,[],[https://swapi.dev/api/films/6/],2014-12-10T12:50:16.526000Z,2014-12-20T20:58:18.440000Z,https://swapi.dev/api/planets/13/
13,Kashyyyk,26,381,12765,tropical,1 standard,"jungle, forests, lakes, rivers",60,45000000,"[https://swapi.dev/api/people/13/, https://swa...",[https://swapi.dev/api/films/6/],2014-12-10T13:32:00.124000Z,2014-12-20T20:58:18.442000Z,https://swapi.dev/api/planets/14/
14,Polis Massa,24,590,0,artificial temperate,0.56 standard,airless asteroid,0,1000000,[],[https://swapi.dev/api/films/6/],2014-12-10T13:33:46.405000Z,2014-12-20T20:58:18.444000Z,https://swapi.dev/api/planets/15/
15,Mygeeto,12,167,10088,frigid,1 standard,"glaciers, mountains, ice canyons",unknown,19000000,[],[https://swapi.dev/api/films/6/],2014-12-10T13:43:39.139000Z,2014-12-20T20:58:18.446000Z,https://swapi.dev/api/planets/16/
16,Felucia,34,231,9100,"hot, humid",0.75 standard,fungus forests,unknown,8500000,[],[https://swapi.dev/api/films/6/],2014-12-10T13:44:50.397000Z,2014-12-20T20:58:18.447000Z,https://swapi.dev/api/planets/17/
17,Cato Neimoidia,25,278,0,"temperate, moist",1 standard,"mountains, fields, forests, rock arches",unknown,10000000,[https://swapi.dev/api/people/33/],[https://swapi.dev/api/films/6/],2014-12-10T13:46:28.704000Z,2014-12-20T20:58:18.449000Z,https://swapi.dev/api/planets/18/
18,Saleucami,26,392,14920,hot,unknown,"caves, desert, mountains, volcanoes",unknown,1400000000,[],[https://swapi.dev/api/films/6/],2014-12-10T13:47:46.874000Z,2014-12-20T20:58:18.450000Z,https://swapi.dev/api/planets/19/
19,Stewjon,unknown,unknown,0,temperate,1 standard,grass,unknown,unknown,[https://swapi.dev/api/people/10/],[],2014-12-10T16:16:26.566000Z,2014-12-20T20:58:18.452000Z,https://swapi.dev/api/planets/20/
20,Eriadu,24,360,13490,polluted,1 standard,cityscape,unknown,22000000000,[https://swapi.dev/api/people/12/],[],2014-12-10T16:26:54.384000Z,2014-12-20T20:58:18.454000Z,https://swapi.dev/api/planets/21/
21,Corellia,25,329,11000,temperate,1 standard,"plains, urban, hills, forests",70,3000000000,"[https://swapi.dev/api/people/14/, https://swa...",[],2014-12-10T16:49:12.453000Z,2014-12-20T20:58:18.456000Z,https://swapi.dev/api/planets/22/
22,Rodia,29,305,7549,hot,1 standard,"jungles, oceans, urban, swamps",60,1300000000,[https://swapi.dev/api/people/15/],[],2014-12-10T17:03:28.110000Z,2014-12-20T20:58:18.458000Z,https://swapi.dev/api/planets/23/
23,Nal Hutta,87,413,12150,temperate,1 standard,"urban, oceans, swamps, bogs",unknown,7000000000,[https://swapi.dev/api/people/16/],[],2014-12-10T17:11:29.452000Z,2014-12-20T20:58:18.460000Z,https://swapi.dev/api/planets/24/
24,Dantooine,25,378,9830,temperate,1 standard,"oceans, savannas, mountains, grasslands",unknown,1000,[],[],2014-12-10T17:23:29.896000Z,2014-12-20T20:58:18.461000Z,https://swapi.dev/api/planets/25/
25,Bestine IV,26,680,6400,temperate,unknown,"rocky islands, oceans",98,62000000,[https://swapi.dev/api/people/19/],[],2014-12-12T11:16:55.078000Z,2014-12-20T20:58:18.463000Z,https://swapi.dev/api/planets/26/
26,Ord Mantell,26,334,14050,temperate,1 standard,"plains, seas, mesas",10,4000000000,[],[https://swapi.dev/api/films/2/],2014-12-15T12:23:41.661000Z,2014-12-20T20:58:18.464000Z,https://swapi.dev/api/planets/27/
27,unknown,0,0,0,unknown,unknown,unknown,unknown,unknown,"[https://swapi.dev/api/people/20/, https://swa...",[],2014-12-15T12:25:59.569000Z,2014-12-20T20:58:18.466000Z,https://swapi.dev/api/planets/28/
28,Trandosha,25,371,0,arid,0.62 standard,"mountains, seas, grasslands, deserts",unknown,42000000,[https://swapi.dev/api/people/24/],[],2014-12-15T12:53:47.695000Z,2014-12-20T20:58:18.468000Z,https://swapi.dev/api/planets/29/
29,Socorro,20,326,0,arid,1 standard,"deserts, mountains",unknown,300000000,[https://swapi.dev/api/people/25/],[],2014-12-15T12:56:31.121000Z,2014-12-20T20:58:18.469000Z,https://swapi.dev/api/planets/30/
30,Mon Cala,21,398,11030,temperate,1,"oceans, reefs, islands",100,27000000000,[https://swapi.dev/api/people/27/],[],2014-12-18T11:07:01.792000Z,2014-12-20T20:58:18.471000Z,https://swapi.dev/api/planets/31/
31,Chandrila,20,368,13500,temperate,1,"plains, forests",40,1200000000,[https://swapi.dev/api/people/28/],[],2014-12-18T11:11:51.872000Z,2014-12-20T20:58:18.472000Z,https://swapi.dev/api/planets/32/
32,Sullust,20,263,12780,superheated,1,"mountains, volcanoes, rocky deserts",5,18500000000,[https://swapi.dev/api/people/31/],[],2014-12-18T11:25:40.243000Z,2014-12-20T20:58:18.474000Z,https://swapi.dev/api/planets/33/
33,Toydaria,21,184,7900,temperate,1,"swamps, lakes",unknown,11000000,[https://swapi.dev/api/people/40/],[],2014-12-19T17:47:54.403000Z,2014-12-20T20:58:18.476000Z,https://swapi.dev/api/planets/34/
34,Malastare,26,201,18880,"arid, temperate, tropical",1.56,"swamps, deserts, jungles, mountains",unknown,2000000000,[https://swapi.dev/api/people/41/],[],2014-12-19T17:52:13.106000Z,2014-12-20T20:58:18.478000Z,https://swapi.dev/api/planets/35/
35,Dathomir,24,491,10480,temperate,0.9,"forests, deserts, savannas",unknown,5200,[https://swapi.dev/api/people/44/],[],2014-12-19T18:00:40.142000Z,2014-12-20T20:58:18.480000Z,https://swapi.dev/api/planets/36/
36,Ryloth,30,305,10600,"temperate, arid, subartic",1,"mountains, valleys, deserts, tundra",5,1500000000,"[https://swapi.dev/api/people/45/, https://swa...",[],2014-12-20T09:46:25.740000Z,2014-12-20T20:58:18.481000Z,https://swapi.dev/api/planets/37/
37,Aleen Minor,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,[https://swapi.dev/api/people/47/],[],2014-12-20T09:52:23.452000Z,2014-12-20T20:58:18.483000Z,https://swapi.dev/api/planets/38/
38,Vulpter,22,391,14900,"temperate, artic",1,"urban, barren",unknown,421000000,[https://swapi.dev/api/people/48/],[],2014-12-20T09:56:58.874000Z,2014-12-20T20:58:18.485000Z,https://swapi.dev/api/planets/39/
39,Troiken,unknown,unknown,unknown,unknown,unknown,"desert, tundra, rainforests, mountains",unknown,unknown,[https://swapi.dev/api/people/49/],[],2014-12-20T10:01:37.395000Z,2014-12-20T20:58:18.487000Z,https://swapi.dev/api/planets/40/
40,Tund,48,1770,12190,unknown,unknown,"barren, ash",unknown,0,[https://swapi.dev/api/people/50/],[],2014-12-20T10:07:29.578000Z,2014-12-20T20:58:18.489000Z,https://swapi.dev/api/planets/41/
41,Haruun Kal,25,383,10120,temperate,0.98,"toxic cloudsea, plateaus, volcanoes",unknown,705300,[https://swapi.dev/api/people/51/],[],2014-12-20T10:12:28.980000Z,2014-12-20T20:58:18.491000Z,https://swapi.dev/api/planets/42/
42,Cerea,27,386,unknown,temperate,1,verdant,20,450000000,[https://swapi.dev/api/people/52/],[],2014-12-20T10:14:48.178000Z,2014-12-20T20:58:18.493000Z,https://swapi.dev/api/planets/43/
43,Glee Anselm,33,206,15600,"tropical, temperate",1,"lakes, islands, swamps, seas",80,500000000,[https://swapi.dev/api/people/53/],[],2014-12-20T10:18:26.110000Z,2014-12-20T20:58:18.495000Z,https://swapi.dev/api/planets/44/
44,Iridonia,29,413,unknown,unknown,unknown,"rocky canyons, acid pools",unknown,unknown,[https://swapi.dev/api/people/54/],[],2014-12-20T10:26:05.788000Z,2014-12-20T20:58:18.497000Z,https://swapi.dev/api/planets/45/
45,Tholoth,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,[],[],2014-12-20T10:28:31.117000Z,2014-12-20T20:58:18.498000Z,https://swapi.dev/api/planets/46/
46,Iktotch,22,481,unknown,"arid, rocky, windy",1,rocky,unknown,unknown,[https://swapi.dev/api/people/56/],[],2014-12-20T10:31:32.413000Z,2014-12-20T20:58:18.500000Z,https://swapi.dev/api/planets/47/
47,Quermia,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,[https://swapi.dev/api/people/57/],[],2014-12-20T10:34:08.249000Z,2014-12-20T20:58:18.502000Z,https://swapi.dev/api/planets/48/
48,Dorin,22,409,13400,temperate,1,unknown,unknown,unknown,[https://swapi.dev/api/people/58/],[],2014-12-20T10:48:36.141000Z,2014-12-20T20:58:18.504000Z,https://swapi.dev/api/planets/49/
49,Champala,27,318,unknown,temperate,1,"oceans, rainforests, plateaus",unknown,3500000000,[https://swapi.dev/api/people/59/],[],2014-12-20T10:52:51.524000Z,2014-12-20T20:58:18.506000Z,https://swapi.dev/api/planets/50/
50,Mirial,unknown,unknown,unknown,unknown,unknown,deserts,unknown,unknown,"[https://swapi.dev/api/people/64/, https://swa...",[],2014-12-20T16:44:46.318000Z,2014-12-20T20:58:18.508000Z,https://swapi.dev/api/planets/51/
51,Serenno,unknown,unknown,unknown,unknown,unknown,"rainforests, rivers, mountains",unknown,unknown,[https://swapi.dev/api/people/67/],[],2014-12-20T16:52:13.357000Z,2014-12-20T20:58:18.510000Z,https://swapi.dev/api/planets/52/
52,Concord Dawn,unknown,unknown,unknown,unknown,unknown,"jungles, forests, deserts",unknown,unknown,[https://swapi.dev/api/people/69/],[],2014-12-20T16:54:39.909000Z,2014-12-20T20:58:18.512000Z,https://swapi.dev/api/planets/53/
53,Zolan,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,[https://swapi.dev/api/people/70/],[],2014-12-20T16:56:37.250000Z,2014-12-20T20:58:18.514000Z,https://swapi.dev/api/planets/54/
54,Ojom,unknown,unknown,unknown,frigid,unknown,"oceans, glaciers",100,500000000,[https://swapi.dev/api/people/71/],[],2014-12-20T17:27:41.286000Z,2014-12-20T20:58:18.516000Z,https://swapi.dev/api/planets/55/
55,Skako,27,384,unknown,temperate,1,"urban, vines",unknown,500000000000,[https://swapi.dev/api/people/76/],[],2014-12-20T17:50:47.864000Z,2014-12-20T20:58:18.517000Z,https://swapi.dev/api/planets/56/
56,Muunilinst,28,412,13800,temperate,1,"plains, forests, hills, mountains",25,5000000000,[https://swapi.dev/api/people/77/],[],2014-12-20T17:57:47.420000Z,2014-12-20T20:58:18.519000Z,https://swapi.dev/api/planets/57/
57,Shili,unknown,unknown,unknown,temperate,1,"cities, savannahs, seas, plains",unknown,unknown,[https://swapi.dev/api/people/78/],[],2014-12-20T18:43:14.049000Z,2014-12-20T20:58:18.521000Z,https://swapi.dev/api/planets/58/
58,Kalee,23,378,13850,"arid, temperate, tropical",1,"rainforests, cliffs, canyons, seas",unknown,4000000000,[https://swapi.dev/api/people/79/],[],2014-12-20T19:43:51.278000Z,2014-12-20T20:58:18.523000Z,https://swapi.dev/api/planets/59/
59,Umbara,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,[https://swapi.dev/api/people/82/],[],2014-12-20T20:18:36.256000Z,2014-12-20T20:58:18.525000Z,https://swapi.dev/api/planets/60/

In [12]:
print('films')
display(df_films_extracted.head())

films

,title,episode_id,opening_crawl,director,producer,release_date,characters,planets,starships,vehicles,species,created,edited,url
0,A New Hope,4,It is a period of civil war.\r\nRebel spaceshi...,George Lucas,"Gary Kurtz, Rick McCallum",1977-05-25,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/planets/1/, https://swa...","[https://swapi.dev/api/starships/2/, https://s...","[https://swapi.dev/api/vehicles/4/, https://sw...","[https://swapi.dev/api/species/1/, https://swa...",2014-12-10T14:23:31.880000Z,2014-12-20T19:49:45.256000Z,https://swapi.dev/api/films/1/
1,The Empire Strikes Back,5,It is a dark time for the\r\nRebellion. Althou...,Irvin Kershner,"Gary Kurtz, Rick McCallum",1980-05-17,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/planets/4/, https://swa...","[https://swapi.dev/api/starships/3/, https://s...","[https://swapi.dev/api/vehicles/8/, https://sw...","[https://swapi.dev/api/species/1/, https://swa...",2014-12-12T11:26:24.656000Z,2014-12-15T13:07:53.386000Z,https://swapi.dev/api/films/2/
2,Return of the Jedi,6,Luke Skywalker has returned to\r\nhis home pla...,Richard Marquand,"Howard G. Kazanjian, George Lucas, Rick McCallum",1983-05-25,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/planets/1/, https://swa...","[https://swapi.dev/api/starships/2/, https://s...","[https://swapi.dev/api/vehicles/8/, https://sw...","[https://swapi.dev/api/species/1/, https://swa...",2014-12-18T10:39:33.255000Z,2014-12-20T09:48:37.462000Z,https://swapi.dev/api/films/3/
3,The Phantom Menace,1,Turmoil has engulfed the\r\nGalactic Republic....,George Lucas,Rick McCallum,1999-05-19,"[https://swapi.dev/api/people/2/, https://swap...","[https://swapi.dev/api/planets/1/, https://swa...","[https://swapi.dev/api/starships/31/, https://...","[https://swapi.dev/api/vehicles/33/, https://s...","[https://swapi.dev/api/species/1/, https://swa...",2014-12-19T16:52:55.740000Z,2014-12-20T10:54:07.216000Z,https://swapi.dev/api/films/4/
4,Attack of the Clones,2,There is unrest in the Galactic\r\nSenate. Sev...,George Lucas,Rick McCallum,2002-05-16,"[https://swapi.dev/api/people/2/, https://swap...","[https://swapi.dev/api/planets/1/, https://swa...","[https://swapi.dev/api/starships/21/, https://...","[https://swapi.dev/api/vehicles/4/, https://sw...","[https://swapi.dev/api/species/1/, https://swa...",2014-12-20T10:57:57.886000Z,2014-12-20T20:18:48.516000Z,https://swapi.dev/api/films/5/

In [13]:
print('species')
display(df_species_extracted.head())

species

,name,classification,designation,average_height,skin_colors,hair_colors,eye_colors,average_lifespan,homeworld,language,people,films,created,edited,url
0,Human,mammal,sentient,180,"caucasian, black, asian, hispanic","blonde, brown, black, red","brown, blue, green, hazel, grey, amber",120,https://swapi.dev/api/planets/9/,Galactic Basic,"[https://swapi.dev/api/people/66/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T13:52:11.567000Z,2014-12-20T21:36:42.136000Z,https://swapi.dev/api/species/1/
1,Droid,artificial,sentient,n/a,n/a,n/a,n/a,indefinite,None,n/a,"[https://swapi.dev/api/people/2/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T15:16:16.259000Z,2014-12-20T21:36:42.139000Z,https://swapi.dev/api/species/2/
2,Wookie,mammal,sentient,210,gray,"black, brown","blue, green, yellow, brown, golden, red",400,https://swapi.dev/api/planets/14/,Shyriiwook,"[https://swapi.dev/api/people/13/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:44:31.486000Z,2014-12-20T21:36:42.142000Z,https://swapi.dev/api/species/3/
3,Rodian,sentient,reptilian,170,"green, blue",n/a,black,unknown,https://swapi.dev/api/planets/23/,Galatic Basic,[https://swapi.dev/api/people/15/],[https://swapi.dev/api/films/1/],2014-12-10T17:05:26.471000Z,2014-12-20T21:36:42.144000Z,https://swapi.dev/api/species/4/
4,Hutt,gastropod,sentient,300,"green, brown, tan",n/a,"yellow, red",1000,https://swapi.dev/api/planets/24/,Huttese,[https://swapi.dev/api/people/16/],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T17:12:50.410000Z,2014-12-20T21:36:42.146000Z,https://swapi.dev/api/species/5/

In [14]:
print('vehicals')
display(df_vehicles_extracted)

vehicals

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,vehicle_class,pilots,films,created,edited,url
0,Sand Crawler,Digger Crawler,Corellia Mining Corporation,150000,36.8,30,46,30,50000,2 months,wheeled,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T15:36:25.724000Z,2014-12-20T21:30:21.661000Z,https://swapi.dev/api/vehicles/4/
1,T-16 skyhopper,T-16 skyhopper,Incom Corporation,14500,10.4,1200,1,1,50,0,repulsorcraft,[],[https://swapi.dev/api/films/1/],2014-12-10T16:01:52.434000Z,2014-12-20T21:30:21.665000Z,https://swapi.dev/api/vehicles/6/
2,X-34 landspeeder,X-34 landspeeder,SoroSuub Corporation,10550,3.4,250,1,1,5,unknown,repulsorcraft,[],[https://swapi.dev/api/films/1/],2014-12-10T16:13:52.586000Z,2014-12-20T21:30:21.668000Z,https://swapi.dev/api/vehicles/7/
3,TIE/LN starfighter,Twin Ion Engine/Ln Starfighter,Sienar Fleet Systems,unknown,6.4,1200,1,0,65,2 days,starfighter,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:33:52.860000Z,2014-12-20T21:30:21.670000Z,https://swapi.dev/api/vehicles/8/
4,Snowspeeder,t-47 airspeeder,Incom corporation,unknown,4.5,650,2,0,10,none,airspeeder,"[https://swapi.dev/api/people/1/, https://swap...",[https://swapi.dev/api/films/2/],2014-12-15T12:22:12Z,2014-12-20T21:30:21.672000Z,https://swapi.dev/api/vehicles/14/
5,TIE bomber,TIE/sa bomber,Sienar Fleet Systems,unknown,7.8,850,1,0,none,2 days,space/planetary bomber,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-15T12:33:15.838000Z,2014-12-20T21:30:21.675000Z,https://swapi.dev/api/vehicles/16/
6,AT-AT,All Terrain Armored Transport,"Kuat Drive Yards, Imperial Department of Milit...",unknown,20,60,5,40,1000,unknown,assault walker,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-15T12:38:25.937000Z,2014-12-20T21:30:21.677000Z,https://swapi.dev/api/vehicles/18/
7,AT-ST,All Terrain Scout Transport,"Kuat Drive Yards, Imperial Department of Milit...",unknown,2,90,2,0,200,none,walker,[https://swapi.dev/api/people/13/],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-15T12:46:42.384000Z,2014-12-20T21:30:21.679000Z,https://swapi.dev/api/vehicles/19/
8,Storm IV Twin-Pod cloud car,Storm IV Twin-Pod,Bespin Motors,75000,7,1500,2,0,10,1 day,repulsorcraft,[],[https://swapi.dev/api/films/2/],2014-12-15T12:58:50.530000Z,2014-12-20T21:30:21.681000Z,https://swapi.dev/api/vehicles/20/
9,Sail barge,Modified Luxury Sail Barge,Ubrikkian Industries Custom Vehicle Division,285000,30,100,26,500,2000000,Live food tanks,sail barge,[],[https://swapi.dev/api/films/3/],2014-12-18T10:44:14.217000Z,2014-12-20T21:30:21.684000Z,https://swapi.dev/api/vehicles/24/
10,Bantha-II cargo skiff,Bantha-II,Ubrikkian Industries,8000,9.5,250,5,16,135000,1 day,repulsorcraft cargo skiff,[],[https://swapi.dev/api/films/3/],2014-12-18T10:48:03.208000Z,2014-12-20T21:30:21.688000Z,https://swapi.dev/api/vehicles/25/
11,TIE/IN interceptor,Twin Ion Engine Interceptor,Sienar Fleet Systems,unknown,9.6,1250,1,0,75,2 days,starfighter,[],[https://swapi.dev/api/films/3/],2014-12-18T10:50:28.225000Z,2014-12-20T21:30:21.691000Z,https://swapi.dev/api/vehicles/26/
12,Imperial Speeder Bike,74-Z speeder bike,Aratech Repulsor Company,8000,3,360,1,1,4,1 day,speeder,"[https://swapi.dev/api/people/1/, https://swap...",[https://swapi.dev/api/films/3/],2014-12-18T11:20:04.625000Z,2014-12-20T21:30:21.693000Z,https://swapi.dev/api/vehicles/30/
13,Vulture Droid,Vulture-class droid starfighter,"Haor Chall Engineering, Baktoid Armor Workshop",unknown,3.5,1200,0,0,0,none,starfighter,[],"[https://swapi.dev/api/films/4/, https://swapi...",2014-12-19T17:09:53.584000Z,2014-12-20T21:30:21.697000Z,https://swapi.dev/api/vehicles/33/
14,Multi-Troop Transport,Multi-Troop Transport,Baktoid Armor Workshop,138000,31,35,4,112,12000,unknown,repulsorcraft,[],[https://swapi.dev/api/films/4/],2014-12-19T17:12:04.400000Z,2014-12-20T21:30:21.700000Z,https://swapi.dev/api/vehicles/34/
15,Armored Assault Tank,Armoured Assault Tank,Baktoid Armor Workshop,unknown,9.75,55,4,6,unknown,unknown,repulsorcraft,[],[https://swapi.dev/api/films/4/],2014-12-19T17:13:29.799000Z,2014-12-20T21:30:21.703000Z,https://swapi.dev/api/vehicles/35/
16,Single Trooper Aerial Platform,Single Trooper Aerial Platform,Baktoid Armor Workshop,2500,2,400,1,0,none,none,repulsorcraft,[],[https://swapi.dev/api/films/4/],2014-12-19T17:15:09.511000Z,2014-12-20T21:30:21.705000Z,https://swapi.dev/api/vehicles/36/
17,C-9979 landing craft,C-9979 landing craft,Haor Chall Engineering,200000,210,587,140,284,1800000,1 day,landing craft,[],[https://swapi.dev/api/films/4/],2014-12-19T17:20:36.373000Z,2014-12-20T21:30:21.707000Z,https://swapi.dev/api/vehicles/37/
18,Tribubble bongo,Tribubble bongo,Otoh Gunga Bongameken Cooperative,unknown,15,85,1,2,1600,unknown,submarine,"[https://swapi.dev/api/people/10/, https://swa...",[https://swapi.dev/api/films/4/],2014-12-19T17:37:37.924000Z,2014-12-20T21:30:21.710000Z,https://swapi.dev/api/vehicles/38/
19,Sith speeder,FC-20 speeder bike,Razalon,4000,1.5,180,1,0,2,unknown,speeder,[https://swapi.dev/api/people/44/],[https://swapi.dev/api/films/4/],2014-12-20T10:09:56.095000Z,2014-12-20T21:30:21.712000Z,https://swapi.dev/api/vehicles/42/
20,Zephyr-G swoop bike,Zephyr-G swoop bike,Mobquet Swoops and Speeders,5750,3.68,350,1,1,200,none,repulsorcraft,[https://swapi.dev/api/people/11/],[https://swapi.dev/api/films/5/],2014-12-20T16:24:16.026000Z,2014-12-20T21:30:21.714000Z,https://swapi.dev/api/vehicles/44/
21,Koro-2 Exodrive airspeeder,Koro-2 Exodrive airspeeder,Desler Gizh Outworld Mobility Corporation,unknown,6.6,800,1,1,80,unknown,airspeeder,[https://swapi.dev/api/people/70/],[https://swapi.dev/api/films/5/],2014-12-20T17:17:33.526000Z,2014-12-20T21:30:21.716000Z,https://swapi.dev/api/vehicles/45/
22,XJ-6 airspeeder,XJ-6 airspeeder,Narglatch AirTech prefabricated kit,unknown,6.23,720,1,1,unknown,unknown,airspeeder,[https://swapi.dev/api/people/11/],[https://swapi.dev/api/films/5/],2014-12-20T17:19:19.991000Z,2014-12-20T21:30:21.719000Z,https://swapi.dev/api/vehicles/46/
23,LAAT/i,Low Altitude Assault Transport/infrantry,Rothana Heavy Engineering,unknown,17.4,620,6,30,170,unknown,gunship,[],"[https://swapi.dev/api/films/5/, https://swapi...",2014-12-20T18:01:21.014000Z,2014-12-20T21:30:21.723000Z,https://swapi.dev/api/vehicles/50/
24,LAAT/c,Low Altitude Assault Transport/carrier,Rothana Heavy Engineering,unknown,28.82,620,1,0,40000,unknown,gunship,[],[https://swapi.dev/api/films/5/],2014-12-20T18:02:46.802000Z,2014-12-20T21:30:21.725000Z,https://swapi.dev/api/vehicles/51/
25,AT-TE,All Terrain Tactical Enforcer,"Rothana Heavy Engineering, Kuat Drive Yards",unknown,13.2,60,6,36,10000,21 days,walker,[],"[https://swapi.dev/api/films/5/, https://swapi...",2014-12-20T18:10:07.560000Z,2014-12-20T21:30:21.728000Z,https://swapi.dev/api/vehicles/53/
26,SPHA,Self-Propelled Heavy Artillery,Rothana Heavy Engineering,unknown,140,35,25,30,500,7 days,walker,[],[https://swapi.dev/api/films/5/],2014-12-20T18:12:32.315000Z,2014-12-20T21:30:21.731000Z,https://swapi.dev/api/vehicles/54/
27,Flitknot speeder,Flitknot speeder,Huppla Pasa Tisc Shipwrights Collective,8000,2,634,1,0,unknown,unknown,speeder,[https://swapi.dev/api/people/67/],[https://swapi.dev/api/films/5/],2014-12-20T18:15:20.312000Z,2014-12-20T21:30:21.735000Z,https://swapi.dev/api/vehicles/55/
28,Neimoidian shuttle,Sheathipede-class transport shuttle,Haor Chall Engineering,unknown,20,880,2,6,1000,7 days,transport,[],"[https://swapi.dev/api/films/5/, https://swapi...",2014-12-20T18:25:44.912000Z,2014-12-20T21:30:21.739000Z,https://swapi.dev/api/vehicles/56/
29,Geonosian starfighter,Nantex-class territorial defense,Huppla Pasa Tisc Shipwrights Collective,unknown,9.8,20000,1,0,unknown,unknown,starfighter,[],[https://swapi.dev/api/films/5/],2014-12-20T18:34:12.541000Z,2014-12-20T21:30:21.742000Z,https://swapi.dev/api/vehicles/57/
30,Tsmeu-6 personal wheel bike,Tsmeu-6 personal wheel bike,Z-Gomot Ternbuell Guppat Corporation,15000,3.5,330,1,1,10,none,wheeled walker,[https://swapi.dev/api/people/79/],[https://swapi.dev/api/films/6/],2014-12-20T19:43:54.870000Z,2014-12-20T21:30:21.745000Z,https://swapi.dev/api/vehicles/60/
31,Emergency Firespeeder,Fire suppression speeder,unknown,unknown,unknown,unknown,2,unknown,unknown,unknown,fire suppression ship,[],[https://swapi.dev/api/films/6/],2014-12-20T19:50:58.559000Z,2014-12-20T21:30:21.749000Z,https://swapi.dev/api/vehicles/62/
32,Droid tri-fighter,tri-fighter,"Colla Designs, Phlac-Arphocc Automata Industries",20000,5.4,1180,1,0,0,none,droid starfighter,[],[https://swapi.dev/api/films/6/],2014-12-20T20:05:19.992000Z,2014-12-20T21:30:21.752000Z,https://swapi.dev/api/vehicles/67/
33,Oevvaor jet catamaran,Oevvaor jet catamaran,Appazanna Engineering Works,12125,15.1,420,2,2,50,3 days,airspeeder,[],[https://swapi.dev/api/films/6/],2014-12-20T20:20:53.931000Z,2014-12-20T21:30:21.756000Z,https://swapi.dev/api/vehicles/69/
34,Raddaugh Gnasp fluttercraft,Raddaugh Gnasp fluttercraft,Appazanna Engineering Works,14750,7,310,2,0,20,none,air speeder,[],[https://swapi.dev/api/films/6/],2014-12-20T20:21:55.648000Z,2014-12-20T21:30:21.759000Z,https://swapi.dev/api/vehicles/70/
35,Clone turbo tank,HAVw A6 Juggernaut,Kuat Drive Yards,350000,49.4,160,20,300,30000,20 days,wheeled walker,[],[https://swapi.dev/api/films/6/],2014-12-20T20:24:45.587000Z,2014-12-20T21:30:21.762000Z,https://swapi.dev/api/vehicles/71/
36,Corporate Alliance tank droid,NR-N99 Persuader-class droid enforcer,Techno Union,49000,10.96,100,0,4,none,none,droid tank,[],[https://swapi.dev/api/films/6/],2014-12-20T20:26:55.522000Z,2014-12-20T21:30:21.765000Z,https://swapi.dev/api/vehicles/72/
37,Droid gunship,HMP droid gunship,"Baktoid Fleet Ordnance, Haor Chall Engineering",60000,12.3,820,0,0,0,none,airspeeder,[],[https://swapi.dev/api/films/6/],2014-12-20T20:32:05.687000Z,2014-12-20T21:30:21.768000Z,https://swapi.dev/api/vehicles/73/
38,AT-RT,All Terrain Recon Transport,Kuat Drive Yards,40000,3.2,90,1,0,20,1 day,walker,[],[https://swapi.dev/api/films/6/],2014-12-20T20:47:49.189000Z,2014-12-20T21:30:21.772000Z,https://swapi.dev/api/vehicles/76/

In [15]:
print('starships')
display(df_starships_extracted.head())

starships

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films,created,edited,url
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,https://swapi.dev/api/starships/2/
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,"1,600",975,"47,060",n/a,36000000,2 years,2.0,60,Star Destroyer,[],"[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,https://swapi.dev/api/starships/3/
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,[],[https://swapi.dev/api/films/1/],2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,https://swapi.dev/api/starships/5/
3,Death Star,DS-1 Orbital Battle Station,"Imperial Department of Military Research, Sien...",1000000000000,120000,n/a,"342,953","843,342",1000000000000,3 years,4.0,10,Deep Space Mobile Battlestation,[],[https://swapi.dev/api/films/1/],2014-12-10T16:36:50.509000Z,2014-12-20T21:26:24.783000Z,https://swapi.dev/api/starships/9/
4,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,"[https://swapi.dev/api/people/13/, https://swa...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/

# Transform

<img style="display: block; margin-left: auto; margin-right: auto; width: 100%;" src="https://dilancroos.com/sw.jpg" alt="banner">

Add the 'id' to all tables<br>
<br>
could be done in two ways
* reset index -> get the index and put it into 'id'<br>
  // df_people_extracted.reset_index().rename(columns={'index':'id'})
* get the id from url

chose to do it with the url method, to make it easy to extract from url from other sources & call the API if needed (even though some urls are not incrementing)

In [16]:
# Create id columns

df_people_extracted[['people_id']] = df_people_extracted[['url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_planets_extracted[['planet_id']] = df_planets_extracted[['url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_films_extracted[['films_id']] = df_films_extracted[['url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_species_extracted[['species_id']] = df_species_extracted[['url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_vehicles_extracted[['vehicales_id']] = df_vehicles_extracted[['url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_starships_extracted[['starships_id']] = df_starships_extracted[['url']].apply(lambda x: x.str.split('/').str[5]).astype(int)

In [17]:
df_people_films_cleaned = (
    df_people_extracted[['people_id', 'films']]
    .explode('films')
    .rename(columns={'films': 'film_url'})
)
df_people_films_cleaned.reset_index(drop=True, inplace=True)
df_people_films_cleaned[['films_id']] = df_people_films_cleaned[['film_url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_people_films_cleaned.drop(columns=['film_url'], inplace=True)
df_people_films_cleaned.head()

   people_id  films_id
0          1         1
1          1         2
2          1         3
3          1         6
4          2         1

In [18]:
df_people_vechicals_piloted_cleaned = (
    df_people_extracted[['people_id', 'vehicles']]
    .explode('vehicles')
    .rename(columns={'vehicles': 'vehicle_url'})
    .dropna(axis=0)

)
df_people_vechicals_piloted_cleaned.reset_index(drop=True, inplace=True)
df_people_vechicals_piloted_cleaned[['vehicles_id']] = df_people_vechicals_piloted_cleaned[['vehicle_url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_people_vechicals_piloted_cleaned.drop(columns=['vehicle_url'], inplace=True)
df_people_vechicals_piloted_cleaned.head()

   people_id  vehicles_id
0          1           14
1          1           30
2          5           30
3         10           38
4         11           44

In [19]:
df_peolpe_starships_piloted_cleaned = (
    df_people_extracted[['people_id', 'starships']]
    .explode('starships')
    .rename(columns={'starships': 'starship_url'})
    .dropna(axis=0)

)
df_peolpe_starships_piloted_cleaned.reset_index(drop=True, inplace=True)
df_peolpe_starships_piloted_cleaned[['starships_id']] = df_peolpe_starships_piloted_cleaned[['starship_url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_peolpe_starships_piloted_cleaned.drop(columns=['starship_url'], inplace=True)
df_peolpe_starships_piloted_cleaned.head()

   people_id  starships_id
0          1            12
1          1            22
2          4            13
3          9            12
4         10            48

In [20]:
df_films_species_cleaned = (
    df_films_extracted[['films_id', 'species']]
    .explode('species')
    .rename(columns={'species': 'species_url'})
    .dropna(axis=0)

)
df_films_species_cleaned.reset_index(drop=True, inplace=True)
df_films_species_cleaned[['species_id']] = df_films_species_cleaned[['species_url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_films_species_cleaned.drop(columns=['species_url'], inplace=True)
df_films_species_cleaned.head()

   films_id  species_id
0         1           1
1         1           2
2         1           3
3         1           4
4         1           5

In [21]:
df_films_planets_cleaned = (
    df_films_extracted[['films_id', 'planets']]
    .explode('planets')
    .rename(columns={'planets': 'planets_url'})
    .dropna(axis=0)

)
df_films_planets_cleaned.reset_index(drop=True, inplace=True)
df_films_planets_cleaned[['planets_id']] = df_films_planets_cleaned[['planets_url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_films_planets_cleaned.drop(columns=['planets_url'], inplace=True)
df_films_planets_cleaned.head()

   films_id  planets_id
0         1           1
1         1           2
2         1           3
3         2           4
4         2           5

In [22]:
df_films_starships_cleaned = (
    df_films_extracted[['films_id', 'starships']]
    .explode('starships')
    .rename(columns={'starships': 'starships_url'})
    .dropna(axis=0)

)
df_films_starships_cleaned.reset_index(drop=True, inplace=True)
df_films_starships_cleaned[['starships_id']] = df_films_starships_cleaned[['starships_url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_films_starships_cleaned.drop(columns=['starships_url'], inplace=True)
df_films_starships_cleaned.head()

   films_id  starships_id
0         1             2
1         1             3
2         1             5
3         1             9
4         1            10

In [23]:
df_films_vehicles_cleaned = (
    df_films_extracted[['films_id', 'vehicles']]
    .explode('vehicles')
    .rename(columns={'vehicles': 'vehicles_url'})
    .rename(columns={'id': 'films_id'})
    .dropna(axis=0)

)
df_films_vehicles_cleaned.reset_index(drop=True, inplace=True)
df_films_vehicles_cleaned[['vehicles_id']] = df_films_vehicles_cleaned[['vehicles_url']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_films_vehicles_cleaned.drop(columns=['vehicles_url'], inplace=True)
df_films_vehicles_cleaned.head(10)

   films_id  vehicles_id
0         1            4
1         1            6
2         1            7
3         1            8
4         2            8
5         2           14
6         2           16
7         2           18
8         2           19
9         2           20

In [24]:
df_people_extracted[['homeworld_id']] = df_people_extracted[['homeworld']].apply(lambda x: x.str.split('/').str[5]).astype(int)
df_people_extracted['species_each'] = df_people_extracted[['species']].explode('species')
df_people_extracted[['species_id']] = df_people_extracted[['species_each']].apply(lambda x: x.str.split('/').str[5])
df_people_extracted['species_id'].fillna(1, inplace=True) # after observation, belive all are human
df_people_extracted['birth_year_BBY'] = df_people_extracted[['birth_year']].apply(lambda x: x.str.replace('BBY',''))
df_people_cleaned = df_people_extracted.drop(columns=['films','vehicles','starships','species','homeworld','species_each','birth_year'])
df_people_cleaned.head(10)

,name,height,mass,hair_color,skin_color,eye_color,gender,created,edited,url,people_id,homeworld_id,species_id,birth_year_BBY
0,Luke Skywalker,172,77,blond,fair,blue,male,2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/,1,1,1,19
1,C-3PO,167,75,n/a,gold,yellow,n/a,2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/,2,1,2,112
2,R2-D2,96,32,n/a,"white, blue",red,n/a,2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/,3,8,2,33
3,Darth Vader,202,136,none,white,yellow,male,2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/,4,1,1,41.9
4,Leia Organa,150,49,brown,light,brown,female,2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/,5,2,1,19
5,Owen Lars,178,120,"brown, grey",light,blue,male,2014-12-10T15:52:14.024000Z,2014-12-20T21:17:50.317000Z,https://swapi.dev/api/people/6/,6,1,1,52
6,Beru Whitesun lars,165,75,brown,light,blue,female,2014-12-10T15:53:41.121000Z,2014-12-20T21:17:50.319000Z,https://swapi.dev/api/people/7/,7,1,1,47
7,R5-D4,97,32,n/a,"white, red",red,n/a,2014-12-10T15:57:50.959000Z,2014-12-20T21:17:50.321000Z,https://swapi.dev/api/people/8/,8,1,2,unknown
8,Biggs Darklighter,183,84,black,light,brown,male,2014-12-10T15:59:50.509000Z,2014-12-20T21:17:50.323000Z,https://swapi.dev/api/people/9/,9,1,1,24
9,Obi-Wan Kenobi,182,77,"auburn, white",fair,blue-gray,male,2014-12-10T16:16:29.192000Z,2014-12-20T21:17:50.325000Z,https://swapi.dev/api/people/10/,10,20,1,57

In [25]:
df_planets_extracted[['gravity']] = df_planets_extracted[['gravity']].apply(lambda x: x.str.split(' ').str[0]) # Taking the first value
df_planets_cleaned =(
    df_planets_extracted
    .drop(columns=['films','residents'])
)
df_planets_cleaned.head(20)

,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,created,edited,url,planet_id
0,Tatooine,23,304,10465,arid,1,desert,1,200000,2014-12-09T13:50:49.641000Z,2014-12-20T20:58:18.411000Z,https://swapi.dev/api/planets/1/,1
1,Alderaan,24,364,12500,temperate,1,"grasslands, mountains",40,2000000000,2014-12-10T11:35:48.479000Z,2014-12-20T20:58:18.420000Z,https://swapi.dev/api/planets/2/,2
2,Yavin IV,24,4818,10200,"temperate, tropical",1,"jungle, rainforests",8,1000,2014-12-10T11:37:19.144000Z,2014-12-20T20:58:18.421000Z,https://swapi.dev/api/planets/3/,3
3,Hoth,23,549,7200,frozen,1.1,"tundra, ice caves, mountain ranges",100,unknown,2014-12-10T11:39:13.934000Z,2014-12-20T20:58:18.423000Z,https://swapi.dev/api/planets/4/,4
4,Dagobah,23,341,8900,murky,N/A,"swamp, jungles",8,unknown,2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,https://swapi.dev/api/planets/5/,5
5,Bespin,12,5110,118000,temperate,1.5,gas giant,0,6000000,2014-12-10T11:43:55.240000Z,2014-12-20T20:58:18.427000Z,https://swapi.dev/api/planets/6/,6
6,Endor,18,402,4900,temperate,0.85,"forests, mountains, lakes",8,30000000,2014-12-10T11:50:29.349000Z,2014-12-20T20:58:18.429000Z,https://swapi.dev/api/planets/7/,7
7,Naboo,26,312,12120,temperate,1,"grassy hills, swamps, forests, mountains",12,4500000000,2014-12-10T11:52:31.066000Z,2014-12-20T20:58:18.430000Z,https://swapi.dev/api/planets/8/,8
8,Coruscant,24,368,12240,temperate,1,"cityscape, mountains",unknown,1000000000000,2014-12-10T11:54:13.921000Z,2014-12-20T20:58:18.432000Z,https://swapi.dev/api/planets/9/,9
9,Kamino,27,463,19720,temperate,1,ocean,100,1000000000,2014-12-10T12:45:06.577000Z,2014-12-20T20:58:18.434000Z,https://swapi.dev/api/planets/10/,10
10,Geonosis,30,256,11370,"temperate, arid",0.9,"rock, desert, mountain, barren",5,100000000000,2014-12-10T12:47:22.350000Z,2014-12-20T20:58:18.437000Z,https://swapi.dev/api/planets/11/,11
11,Utapau,27,351,12900,"temperate, arid, windy",1,"scrublands, savanna, canyons, sinkholes",0.9,95000000,2014-12-10T12:49:01.491000Z,2014-12-20T20:58:18.439000Z,https://swapi.dev/api/planets/12/,12
12,Mustafar,36,412,4200,hot,1,"volcanoes, lava rivers, mountains, caves",0,20000,2014-12-10T12:50:16.526000Z,2014-12-20T20:58:18.440000Z,https://swapi.dev/api/planets/13/,13
13,Kashyyyk,26,381,12765,tropical,1,"jungle, forests, lakes, rivers",60,45000000,2014-12-10T13:32:00.124000Z,2014-12-20T20:58:18.442000Z,https://swapi.dev/api/planets/14/,14
14,Polis Massa,24,590,0,artificial temperate,0.56,airless asteroid,0,1000000,2014-12-10T13:33:46.405000Z,2014-12-20T20:58:18.444000Z,https://swapi.dev/api/planets/15/,15
15,Mygeeto,12,167,10088,frigid,1,"glaciers, mountains, ice canyons",unknown,19000000,2014-12-10T13:43:39.139000Z,2014-12-20T20:58:18.446000Z,https://swapi.dev/api/planets/16/,16
16,Felucia,34,231,9100,"hot, humid",0.75,fungus forests,unknown,8500000,2014-12-10T13:44:50.397000Z,2014-12-20T20:58:18.447000Z,https://swapi.dev/api/planets/17/,17
17,Cato Neimoidia,25,278,0,"temperate, moist",1,"mountains, fields, forests, rock arches",unknown,10000000,2014-12-10T13:46:28.704000Z,2014-12-20T20:58:18.449000Z,https://swapi.dev/api/planets/18/,18
18,Saleucami,26,392,14920,hot,unknown,"caves, desert, mountains, volcanoes",unknown,1400000000,2014-12-10T13:47:46.874000Z,2014-12-20T20:58:18.450000Z,https://swapi.dev/api/planets/19/,19
19,Stewjon,unknown,unknown,0,temperate,1,grass,unknown,unknown,2014-12-10T16:16:26.566000Z,2014-12-20T20:58:18.452000Z,https://swapi.dev/api/planets/20/,20

In [26]:
df_films_cleaned =(
    df_films_extracted
    .drop(columns=['characters','planets','starships','vehicles','species'])
)
df_films_cleaned.head()

,title,episode_id,opening_crawl,director,producer,release_date,created,edited,url,films_id
0,A New Hope,4,It is a period of civil war.\r\nRebel spaceshi...,George Lucas,"Gary Kurtz, Rick McCallum",1977-05-25,2014-12-10T14:23:31.880000Z,2014-12-20T19:49:45.256000Z,https://swapi.dev/api/films/1/,1
1,The Empire Strikes Back,5,It is a dark time for the\r\nRebellion. Althou...,Irvin Kershner,"Gary Kurtz, Rick McCallum",1980-05-17,2014-12-12T11:26:24.656000Z,2014-12-15T13:07:53.386000Z,https://swapi.dev/api/films/2/,2
2,Return of the Jedi,6,Luke Skywalker has returned to\r\nhis home pla...,Richard Marquand,"Howard G. Kazanjian, George Lucas, Rick McCallum",1983-05-25,2014-12-18T10:39:33.255000Z,2014-12-20T09:48:37.462000Z,https://swapi.dev/api/films/3/,3
3,The Phantom Menace,1,Turmoil has engulfed the\r\nGalactic Republic....,George Lucas,Rick McCallum,1999-05-19,2014-12-19T16:52:55.740000Z,2014-12-20T10:54:07.216000Z,https://swapi.dev/api/films/4/,4
4,Attack of the Clones,2,There is unrest in the Galactic\r\nSenate. Sev...,George Lucas,Rick McCallum,2002-05-16,2014-12-20T10:57:57.886000Z,2014-12-20T20:18:48.516000Z,https://swapi.dev/api/films/5/,5

In [27]:
df_species_extracted[['homeworld_id']] = df_species_extracted[['homeworld']].apply(lambda x: x.str.split('/').str[5])
df_species_cleaned = (
    df_species_extracted
    .drop(columns=['films','people','homeworld'])
)
df_species_cleaned.head(20)
# Species_id = 0 is unknown

,name,classification,designation,average_height,skin_colors,hair_colors,eye_colors,average_lifespan,language,created,edited,url,species_id,homeworld_id
0,Human,mammal,sentient,180,"caucasian, black, asian, hispanic","blonde, brown, black, red","brown, blue, green, hazel, grey, amber",120,Galactic Basic,2014-12-10T13:52:11.567000Z,2014-12-20T21:36:42.136000Z,https://swapi.dev/api/species/1/,1,9
1,Droid,artificial,sentient,n/a,n/a,n/a,n/a,indefinite,n/a,2014-12-10T15:16:16.259000Z,2014-12-20T21:36:42.139000Z,https://swapi.dev/api/species/2/,2,None
2,Wookie,mammal,sentient,210,gray,"black, brown","blue, green, yellow, brown, golden, red",400,Shyriiwook,2014-12-10T16:44:31.486000Z,2014-12-20T21:36:42.142000Z,https://swapi.dev/api/species/3/,3,14
3,Rodian,sentient,reptilian,170,"green, blue",n/a,black,unknown,Galatic Basic,2014-12-10T17:05:26.471000Z,2014-12-20T21:36:42.144000Z,https://swapi.dev/api/species/4/,4,23
4,Hutt,gastropod,sentient,300,"green, brown, tan",n/a,"yellow, red",1000,Huttese,2014-12-10T17:12:50.410000Z,2014-12-20T21:36:42.146000Z,https://swapi.dev/api/species/5/,5,24
5,Yoda's species,mammal,sentient,66,"green, yellow","brown, white","brown, green, yellow",900,Galactic basic,2014-12-15T12:27:22.877000Z,2014-12-20T21:36:42.148000Z,https://swapi.dev/api/species/6/,6,28
6,Trandoshan,reptile,sentient,200,"brown, green",none,"yellow, orange",unknown,Dosh,2014-12-15T13:07:47.704000Z,2014-12-20T21:36:42.151000Z,https://swapi.dev/api/species/7/,7,29
7,Mon Calamari,amphibian,sentient,160,"red, blue, brown, magenta",none,yellow,unknown,Mon Calamarian,2014-12-18T11:09:52.263000Z,2014-12-20T21:36:42.153000Z,https://swapi.dev/api/species/8/,8,31
8,Ewok,mammal,sentient,100,brown,"white, brown, black","orange, brown",unknown,Ewokese,2014-12-18T11:22:00.285000Z,2014-12-20T21:36:42.155000Z,https://swapi.dev/api/species/9/,9,7
9,Sullustan,mammal,sentient,180,pale,none,black,unknown,Sullutese,2014-12-18T11:26:20.103000Z,2014-12-20T21:36:42.157000Z,https://swapi.dev/api/species/10/,10,33
10,Neimodian,unknown,sentient,180,"grey, green",none,"red, pink",unknown,Neimoidia,2014-12-19T17:07:31.319000Z,2014-12-20T21:36:42.160000Z,https://swapi.dev/api/species/11/,11,18
11,Gungan,amphibian,sentient,190,"brown, green",none,orange,unknown,Gungan basic,2014-12-19T17:30:37.341000Z,2014-12-20T21:36:42.163000Z,https://swapi.dev/api/species/12/,12,8
12,Toydarian,mammal,sentient,120,"blue, green, grey",none,yellow,91,Toydarian,2014-12-19T17:48:56.893000Z,2014-12-20T21:36:42.165000Z,https://swapi.dev/api/species/13/,13,34
13,Dug,mammal,sentient,100,"brown, purple, grey, red",none,"yellow, blue",unknown,Dugese,2014-12-19T17:53:11.214000Z,2014-12-20T21:36:42.167000Z,https://swapi.dev/api/species/14/,14,35
14,Twi'lek,mammals,sentient,200,"orange, yellow, blue, green, pink, purple, tan",none,"blue, brown, orange, pink",unknown,Twi'leki,2014-12-20T09:48:02.406000Z,2014-12-20T21:36:42.169000Z,https://swapi.dev/api/species/15/,15,37
15,Aleena,reptile,sentient,80,"blue, gray",none,unknown,79,Aleena,2014-12-20T09:53:16.481000Z,2014-12-20T21:36:42.171000Z,https://swapi.dev/api/species/16/,16,38
16,Vulptereen,unknown,sentient,100,grey,none,yellow,unknown,vulpterish,2014-12-20T09:57:33.128000Z,2014-12-20T21:36:42.173000Z,https://swapi.dev/api/species/17/,17,39
17,Xexto,unknown,sentient,125,"grey, yellow, purple",none,black,unknown,Xextese,2014-12-20T10:02:13.915000Z,2014-12-20T21:36:42.175000Z,https://swapi.dev/api/species/18/,18,40
18,Toong,unknown,sentient,200,"grey, green, yellow",none,orange,unknown,Tundan,2014-12-20T10:08:36.795000Z,2014-12-20T21:36:42.177000Z,https://swapi.dev/api/species/19/,19,41
19,Cerean,mammal,sentient,200,pale pink,"red, blond, black, white",hazel,unknown,Cerean,2014-12-20T10:15:33.765000Z,2014-12-20T21:36:42.179000Z,https://swapi.dev/api/species/20/,20,43

In [28]:
df_vehicles_cleaned = (
    df_vehicles_extracted
    .drop(columns=['films','pilots'])
)
df_vehicles_cleaned

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,vehicle_class,created,edited,url,vehicales_id
0,Sand Crawler,Digger Crawler,Corellia Mining Corporation,150000,36.8,30,46,30,50000,2 months,wheeled,2014-12-10T15:36:25.724000Z,2014-12-20T21:30:21.661000Z,https://swapi.dev/api/vehicles/4/,4
1,T-16 skyhopper,T-16 skyhopper,Incom Corporation,14500,10.4,1200,1,1,50,0,repulsorcraft,2014-12-10T16:01:52.434000Z,2014-12-20T21:30:21.665000Z,https://swapi.dev/api/vehicles/6/,6
2,X-34 landspeeder,X-34 landspeeder,SoroSuub Corporation,10550,3.4,250,1,1,5,unknown,repulsorcraft,2014-12-10T16:13:52.586000Z,2014-12-20T21:30:21.668000Z,https://swapi.dev/api/vehicles/7/,7
3,TIE/LN starfighter,Twin Ion Engine/Ln Starfighter,Sienar Fleet Systems,unknown,6.4,1200,1,0,65,2 days,starfighter,2014-12-10T16:33:52.860000Z,2014-12-20T21:30:21.670000Z,https://swapi.dev/api/vehicles/8/,8
4,Snowspeeder,t-47 airspeeder,Incom corporation,unknown,4.5,650,2,0,10,none,airspeeder,2014-12-15T12:22:12Z,2014-12-20T21:30:21.672000Z,https://swapi.dev/api/vehicles/14/,14
5,TIE bomber,TIE/sa bomber,Sienar Fleet Systems,unknown,7.8,850,1,0,none,2 days,space/planetary bomber,2014-12-15T12:33:15.838000Z,2014-12-20T21:30:21.675000Z,https://swapi.dev/api/vehicles/16/,16
6,AT-AT,All Terrain Armored Transport,"Kuat Drive Yards, Imperial Department of Milit...",unknown,20,60,5,40,1000,unknown,assault walker,2014-12-15T12:38:25.937000Z,2014-12-20T21:30:21.677000Z,https://swapi.dev/api/vehicles/18/,18
7,AT-ST,All Terrain Scout Transport,"Kuat Drive Yards, Imperial Department of Milit...",unknown,2,90,2,0,200,none,walker,2014-12-15T12:46:42.384000Z,2014-12-20T21:30:21.679000Z,https://swapi.dev/api/vehicles/19/,19
8,Storm IV Twin-Pod cloud car,Storm IV Twin-Pod,Bespin Motors,75000,7,1500,2,0,10,1 day,repulsorcraft,2014-12-15T12:58:50.530000Z,2014-12-20T21:30:21.681000Z,https://swapi.dev/api/vehicles/20/,20
9,Sail barge,Modified Luxury Sail Barge,Ubrikkian Industries Custom Vehicle Division,285000,30,100,26,500,2000000,Live food tanks,sail barge,2014-12-18T10:44:14.217000Z,2014-12-20T21:30:21.684000Z,https://swapi.dev/api/vehicles/24/,24
10,Bantha-II cargo skiff,Bantha-II,Ubrikkian Industries,8000,9.5,250,5,16,135000,1 day,repulsorcraft cargo skiff,2014-12-18T10:48:03.208000Z,2014-12-20T21:30:21.688000Z,https://swapi.dev/api/vehicles/25/,25
11,TIE/IN interceptor,Twin Ion Engine Interceptor,Sienar Fleet Systems,unknown,9.6,1250,1,0,75,2 days,starfighter,2014-12-18T10:50:28.225000Z,2014-12-20T21:30:21.691000Z,https://swapi.dev/api/vehicles/26/,26
12,Imperial Speeder Bike,74-Z speeder bike,Aratech Repulsor Company,8000,3,360,1,1,4,1 day,speeder,2014-12-18T11:20:04.625000Z,2014-12-20T21:30:21.693000Z,https://swapi.dev/api/vehicles/30/,30
13,Vulture Droid,Vulture-class droid starfighter,"Haor Chall Engineering, Baktoid Armor Workshop",unknown,3.5,1200,0,0,0,none,starfighter,2014-12-19T17:09:53.584000Z,2014-12-20T21:30:21.697000Z,https://swapi.dev/api/vehicles/33/,33
14,Multi-Troop Transport,Multi-Troop Transport,Baktoid Armor Workshop,138000,31,35,4,112,12000,unknown,repulsorcraft,2014-12-19T17:12:04.400000Z,2014-12-20T21:30:21.700000Z,https://swapi.dev/api/vehicles/34/,34
15,Armored Assault Tank,Armoured Assault Tank,Baktoid Armor Workshop,unknown,9.75,55,4,6,unknown,unknown,repulsorcraft,2014-12-19T17:13:29.799000Z,2014-12-20T21:30:21.703000Z,https://swapi.dev/api/vehicles/35/,35
16,Single Trooper Aerial Platform,Single Trooper Aerial Platform,Baktoid Armor Workshop,2500,2,400,1,0,none,none,repulsorcraft,2014-12-19T17:15:09.511000Z,2014-12-20T21:30:21.705000Z,https://swapi.dev/api/vehicles/36/,36
17,C-9979 landing craft,C-9979 landing craft,Haor Chall Engineering,200000,210,587,140,284,1800000,1 day,landing craft,2014-12-19T17:20:36.373000Z,2014-12-20T21:30:21.707000Z,https://swapi.dev/api/vehicles/37/,37
18,Tribubble bongo,Tribubble bongo,Otoh Gunga Bongameken Cooperative,unknown,15,85,1,2,1600,unknown,submarine,2014-12-19T17:37:37.924000Z,2014-12-20T21:30:21.710000Z,https://swapi.dev/api/vehicles/38/,38
19,Sith speeder,FC-20 speeder bike,Razalon,4000,1.5,180,1,0,2,unknown,speeder,2014-12-20T10:09:56.095000Z,2014-12-20T21:30:21.712000Z,https://swapi.dev/api/vehicles/42/,42
20,Zephyr-G swoop bike,Zephyr-G swoop bike,Mobquet Swoops and Speeders,5750,3.68,350,1,1,200,none,repulsorcraft,2014-12-20T16:24:16.026000Z,2014-12-20T21:30:21.714000Z,https://swapi.dev/api/vehicles/44/,44
21,Koro-2 Exodrive airspeeder,Koro-2 Exodrive airspeeder,Desler Gizh Outworld Mobility Corporation,unknown,6.6,800,1,1,80,unknown,airspeeder,2014-12-20T17:17:33.526000Z,2014-12-20T21:30:21.716000Z,https://swapi.dev/api/vehicles/45/,45
22,XJ-6 airspeeder,XJ-6 airspeeder,Narglatch AirTech prefabricated kit,unknown,6.23,720,1,1,unknown,unknown,airspeeder,2014-12-20T17:19:19.991000Z,2014-12-20T21:30:21.719000Z,https://swapi.dev/api/vehicles/46/,46
23,LAAT/i,Low Altitude Assault Transport/infrantry,Rothana Heavy Engineering,unknown,17.4,620,6,30,170,unknown,gunship,2014-12-20T18:01:21.014000Z,2014-12-20T21:30:21.723000Z,https://swapi.dev/api/vehicles/50/,50
24,LAAT/c,Low Altitude Assault Transport/carrier,Rothana Heavy Engineering,unknown,28.82,620,1,0,40000,unknown,gunship,2014-12-20T18:02:46.802000Z,2014-12-20T21:30:21.725000Z,https://swapi.dev/api/vehicles/51/,51
25,AT-TE,All Terrain Tactical Enforcer,"Rothana Heavy Engineering, Kuat Drive Yards",unknown,13.2,60,6,36,10000,21 days,walker,2014-12-20T18:10:07.560000Z,2014-12-20T21:30:21.728000Z,https://swapi.dev/api/vehicles/53/,53
26,SPHA,Self-Propelled Heavy Artillery,Rothana Heavy Engineering,unknown,140,35,25,30,500,7 days,walker,2014-12-20T18:12:32.315000Z,2014-12-20T21:30:21.731000Z,https://swapi.dev/api/vehicles/54/,54
27,Flitknot speeder,Flitknot speeder,Huppla Pasa Tisc Shipwrights Collective,8000,2,634,1,0,unknown,unknown,speeder,2014-12-20T18:15:20.312000Z,2014-12-20T21:30:21.735000Z,https://swapi.dev/api/vehicles/55/,55
28,Neimoidian shuttle,Sheathipede-class transport shuttle,Haor Chall Engineering,unknown,20,880,2,6,1000,7 days,transport,2014-12-20T18:25:44.912000Z,2014-12-20T21:30:21.739000Z,https://swapi.dev/api/vehicles/56/,56
29,Geonosian starfighter,Nantex-class territorial defense,Huppla Pasa Tisc Shipwrights Collective,unknown,9.8,20000,1,0,unknown,unknown,starfighter,2014-12-20T18:34:12.541000Z,2014-12-20T21:30:21.742000Z,https://swapi.dev/api/vehicles/57/,57
30,Tsmeu-6 personal wheel bike,Tsmeu-6 personal wheel bike,Z-Gomot Ternbuell Guppat Corporation,15000,3.5,330,1,1,10,none,wheeled walker,2014-12-20T19:43:54.870000Z,2014-12-20T21:30:21.745000Z,https://swapi.dev/api/vehicles/60/,60
31,Emergency Firespeeder,Fire suppression speeder,unknown,unknown,unknown,unknown,2,unknown,unknown,unknown,fire suppression ship,2014-12-20T19:50:58.559000Z,2014-12-20T21:30:21.749000Z,https://swapi.dev/api/vehicles/62/,62
32,Droid tri-fighter,tri-fighter,"Colla Designs, Phlac-Arphocc Automata Industries",20000,5.4,1180,1,0,0,none,droid starfighter,2014-12-20T20:05:19.992000Z,2014-12-20T21:30:21.752000Z,https://swapi.dev/api/vehicles/67/,67
33,Oevvaor jet catamaran,Oevvaor jet catamaran,Appazanna Engineering Works,12125,15.1,420,2,2,50,3 days,airspeeder,2014-12-20T20:20:53.931000Z,2014-12-20T21:30:21.756000Z,https://swapi.dev/api/vehicles/69/,69
34,Raddaugh Gnasp fluttercraft,Raddaugh Gnasp fluttercraft,Appazanna Engineering Works,14750,7,310,2,0,20,none,air speeder,2014-12-20T20:21:55.648000Z,2014-12-20T21:30:21.759000Z,https://swapi.dev/api/vehicles/70/,70
35,Clone turbo tank,HAVw A6 Juggernaut,Kuat Drive Yards,350000,49.4,160,20,300,30000,20 days,wheeled walker,2014-12-20T20:24:45.587000Z,2014-12-20T21:30:21.762000Z,https://swapi.dev/api/vehicles/71/,71
36,Corporate Alliance tank droid,NR-N99 Persuader-class droid enforcer,Techno Union,49000,10.96,100,0,4,none,none,droid tank,2014-12-20T20:26:55.522000Z,2014-12-20T21:30:21.765000Z,https://swapi.dev/api/vehicles/72/,72
37,Droid gunship,HMP droid gunship,"Baktoid Fleet Ordnance, Haor Chall Engineering",60000,12.3,820,0,0,0,none,airspeeder,2014-12-20T20:32:05.687000Z,2014-12-20T21:30:21.768000Z,https://swapi.dev/api/vehicles/73/,73
38,AT-RT,All Terrain Recon Transport,Kuat Drive Yards,40000,3.2,90,1,0,20,1 day,walker,2014-12-20T20:47:49.189000Z,2014-12-20T21:30:21.772000Z,https://swapi.dev/api/vehicles/76/,76

In [29]:
df_starships_extracted['crew'].replace(',', '', regex=True, inplace=True)
df_starships_extracted['passengers'].replace(',', '', regex=True, inplace=True)
df_starships_extracted['length'].replace(',', '', regex=True, inplace=True)
df_starships_extracted['max_atmosphering_speed'].replace('km', '', regex=True, inplace=True)
df_starship_cleaned = (
    df_starships_extracted
    .drop(columns=['films','pilots'])
)
df_starship_cleaned.head(20)

,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,created,edited,url,starships_id
0,CR90 corvette,CR90 corvette,Corellian Engineering Corporation,3500000,150,950,30-165,600,3000000,1 year,2.0,60,corvette,2014-12-10T14:20:33.369000Z,2014-12-20T21:23:49.867000Z,https://swapi.dev/api/starships/2/,2
1,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,150000000,1600,975,47060,n/a,36000000,2 years,2.0,60,Star Destroyer,2014-12-10T15:08:19.848000Z,2014-12-20T21:23:49.870000Z,https://swapi.dev/api/starships/3/,3
2,Sentinel-class landing craft,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",240000,38,1000,5,75,180000,1 month,1.0,70,landing craft,2014-12-10T15:48:00.586000Z,2014-12-20T21:23:49.873000Z,https://swapi.dev/api/starships/5/,5
3,Death Star,DS-1 Orbital Battle Station,"Imperial Department of Military Research, Sien...",1000000000000,120000,n/a,342953,843342,1000000000000,3 years,4.0,10,Deep Space Mobile Battlestation,2014-12-10T16:36:50.509000Z,2014-12-20T21:26:24.783000Z,https://swapi.dev/api/starships/9/,9
4,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,100000,34.37,1050,4,6,100000,2 months,0.5,75,Light freighter,2014-12-10T16:59:45.094000Z,2014-12-20T21:23:49.880000Z,https://swapi.dev/api/starships/10/,10
5,Y-wing,BTL Y-wing,Koensayr Manufacturing,134999,14,1000,2,0,110,1 week,1.0,80,assault starfighter,2014-12-12T11:00:39.817000Z,2014-12-20T21:23:49.883000Z,https://swapi.dev/api/starships/11/,11
6,X-wing,T-65 X-wing,Incom Corporation,149999,12.5,1050,1,0,110,1 week,1.0,100,Starfighter,2014-12-12T11:19:05.340000Z,2014-12-20T21:23:49.886000Z,https://swapi.dev/api/starships/12/,12
7,TIE Advanced x1,Twin Ion Engine Advanced x1,Sienar Fleet Systems,unknown,9.2,1200,1,0,150,5 days,1.0,105,Starfighter,2014-12-12T11:21:32.991000Z,2014-12-20T21:23:49.889000Z,https://swapi.dev/api/starships/13/,13
8,Executor,Executor-class star dreadnought,"Kuat Drive Yards, Fondor Shipyards",1143350000,19000,n/a,279144,38000,250000000,6 years,2.0,40,Star dreadnought,2014-12-15T12:31:42.547000Z,2014-12-20T21:23:49.893000Z,https://swapi.dev/api/starships/15/,15
9,Rebel transport,GR-75 medium transport,"Gallofree Yards, Inc.",unknown,90,650,6,90,19000000,6 months,4.0,20,Medium transport,2014-12-15T12:34:52.264000Z,2014-12-20T21:23:49.895000Z,https://swapi.dev/api/starships/17/,17
10,Slave 1,Firespray-31-class patrol and attack,Kuat Systems Engineering,unknown,21.5,1000,1,6,70000,1 month,3.0,70,Patrol craft,2014-12-15T13:00:56.332000Z,2014-12-20T21:23:49.897000Z,https://swapi.dev/api/starships/21/,21
11,Imperial shuttle,Lambda-class T-4a shuttle,Sienar Fleet Systems,240000,20,850,6,20,80000,2 months,1.0,50,Armed government transport,2014-12-15T13:04:47.235000Z,2014-12-20T21:23:49.900000Z,https://swapi.dev/api/starships/22/,22
12,EF76 Nebulon-B escort frigate,EF76 Nebulon-B escort frigate,Kuat Drive Yards,8500000,300,800,854,75,6000000,2 years,2.0,40,Escort ship,2014-12-15T13:06:30.813000Z,2014-12-20T21:23:49.902000Z,https://swapi.dev/api/starships/23/,23
13,Calamari Cruiser,MC80 Liberty type Star Cruiser,Mon Calamari shipyards,104000000,1200,n/a,5400,1200,unknown,2 years,1.0,60,Star Cruiser,2014-12-18T10:54:57.804000Z,2014-12-20T21:23:49.904000Z,https://swapi.dev/api/starships/27/,27
14,A-wing,RZ-1 A-wing Interceptor,"Alliance Underground Engineering, Incom Corpor...",175000,9.6,1300,1,0,40,1 week,1.0,120,Starfighter,2014-12-18T11:16:34.542000Z,2014-12-20T21:23:49.907000Z,https://swapi.dev/api/starships/28/,28
15,B-wing,A/SF-01 B-wing starfighter,Slayn & Korpil,220000,16.9,950,1,0,45,1 week,2.0,91,Assault Starfighter,2014-12-18T11:18:04.763000Z,2014-12-20T21:23:49.909000Z,https://swapi.dev/api/starships/29/,29
16,Republic Cruiser,Consular-class cruiser,Corellian Engineering Corporation,unknown,115,900,9,16,unknown,unknown,2.0,unknown,Space cruiser,2014-12-19T17:01:31.488000Z,2014-12-20T21:23:49.912000Z,https://swapi.dev/api/starships/31/,31
17,Droid control ship,Lucrehulk-class Droid Control Ship,"Hoersch-Kessel Drive, Inc.",unknown,3170,n/a,175,139000,4000000000,500 days,2.0,unknown,Droid control ship,2014-12-19T17:04:06.323000Z,2014-12-20T21:23:49.915000Z,https://swapi.dev/api/starships/32/,32
18,Naboo fighter,N-1 starfighter,Theed Palace Space Vessel Engineering Corps,200000,11,1100,1,0,65,7 days,1.0,unknown,Starfighter,2014-12-19T17:39:17.582000Z,2014-12-20T21:23:49.917000Z,https://swapi.dev/api/starships/39/,39
19,Naboo Royal Starship,J-type 327 Nubian royal starship,"Theed Palace Space Vessel Engineering Corps, N...",unknown,76,920,8,unknown,unknown,unknown,1.8,unknown,yacht,2014-12-19T17:45:03.506000Z,2014-12-20T21:23:49.919000Z,https://swapi.dev/api/starships/40/,40

# Load

In [30]:
# Connect to database

conn = sqlite3.connect('starwars.db')
c = conn.cursor()

# Drop tables if they exist

c.execute('DROP TABLE IF EXISTS people')
c.execute('DROP TABLE IF EXISTS planets')
c.execute('DROP TABLE IF EXISTS films')
c.execute('DROP TABLE IF EXISTS species')
c.execute('DROP TABLE IF EXISTS vehicles')
c.execute('DROP TABLE IF EXISTS starships')
c.execute('DROP TABLE IF EXISTS people_films')
c.execute('DROP TABLE IF EXISTS people_vehicles')
c.execute('DROP TABLE IF EXISTS people_starships')
c.execute('DROP TABLE IF EXISTS films_species')
c.execute('DROP TABLE IF EXISTS films_planets')
c.execute('DROP TABLE IF EXISTS films_starships')
c.execute('DROP TABLE IF EXISTS films_vehicles')

# Create tables

c.execute(f"CREATE TABLE IF NOT EXISTS people ({', '.join(df_people_cleaned.columns)});")
conn.commit()
df_people_cleaned.to_sql('people', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS planets ({', '.join(df_planets_cleaned.columns)});")
conn.commit()
df_planets_cleaned.to_sql('planets', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS films ({', '.join(df_films_cleaned.columns)});")
conn.commit()
df_films_cleaned.to_sql('films', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS species ({', '.join(df_species_cleaned.columns)});")
conn.commit()
df_species_cleaned.to_sql('species', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS vehicles ({', '.join(df_vehicles_cleaned.columns)});")
conn.commit()
df_vehicles_cleaned.to_sql('vehicles', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS starships ({', '.join(df_starship_cleaned.columns)});")
conn.commit()
df_starship_cleaned.to_sql('starships', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS people_films ({', '.join(df_people_films_cleaned.columns)});")
conn.commit()
df_people_films_cleaned.to_sql('people_films', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS people_vehicles ({', '.join(df_people_vechicals_piloted_cleaned.columns)});")
conn.commit()
df_people_vechicals_piloted_cleaned.to_sql('people_vehicles', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS people_starships ({', '.join(df_peolpe_starships_piloted_cleaned.columns)});")
conn.commit()
df_peolpe_starships_piloted_cleaned.to_sql('people_starships', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS films_species ({', '.join(df_films_species_cleaned.columns)});")
conn.commit()
df_films_species_cleaned.to_sql('films_species', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS films_planets ({', '.join(df_films_planets_cleaned.columns)});")
conn.commit()
df_films_planets_cleaned.to_sql('films_planets', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS films_starships ({', '.join(df_films_starships_cleaned.columns)});")
conn.commit()
df_films_starships_cleaned.to_sql('films_starships', conn, if_exists='replace', index=False)

c.execute(f"CREATE TABLE IF NOT EXISTS films_vehicles ({', '.join(df_films_vehicles_cleaned.columns)});")
conn.commit()
df_films_vehicles_cleaned.to_sql('films_vehicles', conn, if_exists='replace', index=False)

49

# Analysis

In [31]:
con = sqlite3.connect('starwars.db')

Do some SQL analysis
- 1 request with INNER
- 1 request with LEFT
- 1 request with GROUP BY
- 1 request with HAVING
- 1 request with CTE<br>
Comment your requests to explain what you wanted to display

In [32]:
# INNER JOIN
# people with a species (mentioned) where person name starts with a 'D'

pd.read_sql_query(
    '''
        SELECT
            p.name AS people_name,
            s.name AS species_name
        FROM
            people AS p
        INNER JOIN
            species AS s ON p.species_id = s.species_id
        WHERE
            p.name LIKE 'D%'

    ''',
    con)

       people_name species_name
0      Darth Vader        Human
1       Darth Maul       Zabrak
2         Dud Bolt   Vulptereen
3            Dormé        Human
4            Dooku        Human
5  Dexter Jettster     Besalisk

In [33]:
# LEFT JOIN
# Top 5 species with the most number people

pd.read_sql_query(
    '''
        SELECT
            sp.name,
            COUNT(*) AS num_people
        FROM
            species AS sp
        LEFT JOIN
            people AS pe ON pe.species_id = sp.species_id
        GROUP BY
            sp.name
        ORDER BY
            num_people DESC
        LIMIT 5
    ''',
    con)

     name  num_people
0   Human          36
1   Droid           4
2  Gungan           3
3  Zabrak           2
4  Wookie           2

In [34]:
# GROUP BY
# Top 5 planets with the most number of people living on them (excluding unknown)

pd.read_sql_query(
    '''
        SELECT
            pl.name,
            COUNT(*) AS num_people
        FROM
            planets AS pl
        INNER JOIN
            people AS pe ON pe.homeworld_id = pl.planet_id
        WHERE 
            pl.name != 'unknown'
        GROUP BY
            pl.name
        ORDER BY
            num_people DESC
        LIMIT 5
    ''',
    con)

        name  num_people
0      Naboo          11
1   Tatooine          10
2     Kamino           3
3  Coruscant           3
4   Alderaan           3

In [35]:
# HAVING
# Get the pilots name and the number of starships he/she has piloted and the starship having a cargo_capacity greater than 100000 and the pilot has piloted more than 1 starship

pd.read_sql_query(
    '''
        SELECT
            p.name AS pilot_name,
            COUNT(*) AS num_starships_piloted
        FROM
            people AS p
        INNER JOIN
            people_starships AS ps ON ps.people_id = p.people_id
        INNER JOIN
            starships AS s ON s.starships_id = ps.starships_id
        GROUP BY
            p.name
        HAVING
            num_starships_piloted > 1 AND s.cargo_capacity > 100000
        ORDER BY
            num_starships_piloted DESC

    ''',
    con)

         pilot_name  num_starships_piloted
0    Obi-Wan Kenobi                      5
1     Padmé Amidala                      3
2  Anakin Skywalker                      3
3    Luke Skywalker                      2

In [36]:
# CTE
# Get the number of starships and vehicles having a cargo_capacity greater than 10000
pd.read_sql_query(
    '''
        WITH starships_cap AS (
            SELECT
                'starship' AS type,
                COUNT(*) AS num_starships_vehicles
            FROM
                starships AS s
            WHERE
                s.cargo_capacity > 10000
        ),
        vehicles_cap AS (
            SELECT
                'vehicle' AS type,
                COUNT(*) AS num_starships_vehicles
            FROM
                vehicles AS v
            WHERE
                v.cargo_capacity > 10000
        )

        SELECT
            *
        FROM
            starships_cap
        
        UNION
        
        SELECT
            *
        FROM
            vehicles_cap
    ''',
    con)

       type  num_starships_vehicles
0  starship                      36
1   vehicle                      30